[env:pro8]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino

check_tool = cppcheck
check_skip_packages = yes

; Keep analysis focused on your code
check_src_filters =
  +<*.h>
  +<*.cpp>
  +<*.ino>
  -<.pio/>
  -<test/>
  -<lib/>

; Optional extra flags for cppcheck
check_flags =
  cppcheck: --inline-suppr
  cppcheck: --std=c++11
  cppcheck: --language=c++
